blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/Alfredo-Sandoval/imgaug2/discussions
    about: For usage questions, check existing discussions or start a new one
